[package]
name = "dnd-calculator"
version = "0.1.0"
authors = ["arbaregni <jamesnsours@gmail.com>"]
edition = "2018"

[dependencies]
pad = "0.1.5"
regex = "1"
lazy_static = "*"
pest = "2.1.2"
pest_derive = "2.1.0"